export const CHANGE_SETTINGS_FORMAT_SQL = 'CHANGE_SETTINGS_FORMAT_SQL'
export const CHANGE_SETTINGS_HIGHLIGHT_SQL = 'CHANGE_SETTINGS_HIGHLIGHT_SQL'
export const CHANGE_MESSAGES_PER_PAGE  = 'CHANGE_MESSAGES_PER_PAGE'
